import type { Property } from './entities/Property';

export const PLATFORM_FEE_RATE = 0.015;

export const mockProperties: Property[] = [
  {
    id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    title: 'Riverside Luxury Apartments',
    location: 'Lisbon, Portugal',
    photoUrls: [
      '/properties/lisbon-apartments.png',
      '/properties/lisbon-apartments.png',
      '/properties/lisbon-apartments.png',
    ],
    totalValue: 320000,
    funded: 72,
    annualYield: 6.8,
    projectedAppreciation: 4.2,
    status: 'open',
    description:
      'Premium waterfront apartments in the heart of Lisbon. Located in the vibrant Alfama district, these fully renovated units offer stunning Tagus River views. Currently generating strong rental income from a mix of long-term tenants and licensed short-term holiday lets.',
    availableShares: 280,
    createdAt: '2026-01-15T10:30:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    title: 'Porto Historic Quarter Townhouse',
    location: 'Porto, Portugal',
    photoUrls: [
      '/properties/porto-townhouse.png',
      '/properties/porto-townhouse.png',
      '/properties/porto-townhouse.png',
    ],
    totalValue: 185000,
    funded: 45,
    annualYield: 7.1,
    projectedAppreciation: 3.8,
    status: 'open',
    description:
      'Charming townhouse in Porto\'s UNESCO-listed Ribeira district. Three residential units, all currently leased with stable tenants. Walking distance to iconic São Bento Station and the famous Dom Luís I Bridge.',
    availableShares: 550,
    createdAt: '2026-02-01T14:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f',
    title: 'Berlin Mitte Studio Collection',
    location: 'Berlin, Germany',
    photoUrls: [
      '/properties/berlin-studios.png',
      '/properties/berlin-studios.png',
      '/properties/berlin-studios.png',
    ],
    totalValue: 450000,
    funded: 100,
    annualYield: 5.4,
    projectedAppreciation: 3.1,
    status: 'funded',
    description:
      'Collection of 6 modern studios in Berlin\'s central Mitte neighbourhood. Fully occupied with young professionals on long-term contracts. Located near Alexanderplatz with excellent public transport links.',
    availableShares: 0,
    createdAt: '2025-11-20T09:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'd4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a',
    title: 'Amsterdam Canal-Side Flat',
    location: 'Amsterdam, Netherlands',
    photoUrls: [
      '/properties/amsterdam-canal.png',
      '/properties/amsterdam-canal.png',
      '/properties/amsterdam-canal.png',
    ],
    totalValue: 520000,
    funded: 33,
    annualYield: 5.9,
    projectedAppreciation: 4.5,
    status: 'open',
    description:
      'Elegant 2-bedroom flat overlooking the Prinsengracht canal. Recently renovated with premium finishes. Strong demand from expat professionals in the Amsterdam market ensures low vacancy rates.',
    availableShares: 670,
    createdAt: '2026-02-20T11:15:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b',
    title: 'Barcelona Eixample Duplex',
    location: 'Barcelona, Spain',
    photoUrls: [
      '/properties/barcelona-duplex.png',
      '/properties/barcelona-duplex.png',
      '/properties/barcelona-duplex.png',
    ],
    totalValue: 380000,
    funded: 0,
    annualYield: 6.3,
    projectedAppreciation: 5.0,
    status: 'coming_soon',
    description:
      'Stunning duplex in Barcelona\'s iconic Eixample district. High ceilings, original mosaic floors, and a private terrace with city views. Ideal for premium mid-term rental strategy targeting digital nomads.',
    availableShares: 1000,
    createdAt: '2026-03-10T08:45:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
    title: 'Dublin Docklands Apartment',
    location: 'Dublin, Ireland',
    photoUrls: [
      '/properties/dublin-docklands.png',
      '/properties/dublin-docklands.png',
      '/properties/dublin-docklands.png',
    ],
    totalValue: 295000,
    funded: 88,
    annualYield: 7.5,
    projectedAppreciation: 3.2,
    status: 'open',
    description:
      'Modern 1-bedroom apartment in Dublin\'s Silicon Docks area, surrounded by tech headquarters. Strong rental demand from tech professionals. Building includes gym, concierge, and underground parking.',
    availableShares: 120,
    createdAt: '2025-12-05T16:30:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d',
    title: 'Milan Fashion District Loft',
    location: 'Milan, Italy',
    photoUrls: [
      '/properties/milan-loft.png',
      '/properties/milan-loft.png',
      '/properties/milan-loft.png',
    ],
    totalValue: 410000,
    funded: 100,
    annualYield: 5.7,
    projectedAppreciation: 4.8,
    status: 'funded',
    description:
      'Industrial-chic loft conversion in Milan\'s Quadrilatero della Moda. Open-plan living with exposed brick and steel beams. Premium short-term rental market driven by fashion industry events.',
    availableShares: 0,
    createdAt: '2025-10-12T13:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e',
    title: 'Vienna Ringstrasse Residence',
    location: 'Vienna, Austria',
    photoUrls: [
      '/properties/vienna-residence.png',
      '/properties/vienna-residence.png',
      '/properties/vienna-residence.png',
    ],
    totalValue: 275000,
    funded: 15,
    annualYield: 8.2,
    projectedAppreciation: 2.9,
    status: 'open',
    description:
      'Elegant 3-bedroom residence near Vienna\'s famous Ringstrasse boulevard. Fully furnished and leased to OPEC employees on a 2-year contract. Exceptional yield driven by triple-net lease structure.',
    availableShares: 850,
    createdAt: '2026-03-20T07:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f',
    title: 'Madrid Gran Via Luxury Suite',
    location: 'Madrid, Spain',
    photoUrls: [
      '/properties/madrid-suite.png',
      '/properties/madrid-suite.png',
      '/properties/madrid-suite.png',
    ],
    totalValue: 550000,
    funded: 40,
    annualYield: 6.2,
    projectedAppreciation: 4.1,
    status: 'open',
    description: 'A luxurious suite located on the famous Gran Via. Features high-end finishes and incredible city views, catering to corporate let markets.',
    availableShares: 450,
    createdAt: '2026-02-15T09:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'd0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a',
    title: 'Rome Trastevere Classic Apartment',
    location: 'Rome, Italy',
    photoUrls: [
      '/properties/rome-apartment.png',
      '/properties/rome-apartment.png',
      '/properties/rome-apartment.png',
    ],
    totalValue: 320000,
    funded: 80,
    annualYield: 7.0,
    projectedAppreciation: 3.5,
    status: 'open',
    description: 'Charming classic apartment in the historic Trastevere neighborhood, ideal for short-term holiday rentals with high year-round demand.',
    availableShares: 120,
    createdAt: '2026-03-05T10:30:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b',
    title: 'Paris Montmartre Studio',
    location: 'Paris, France',
    photoUrls: [
      '/properties/paris-studio.png',
      '/properties/paris-studio.png',
      '/properties/paris-studio.png',
    ],
    totalValue: 410000,
    funded: 100,
    annualYield: 5.5,
    projectedAppreciation: 4.8,
    status: 'funded',
    description: 'Cozy and bright studio in the heart of Montmartre. Fully renovated and currently rented to a young professional on a long-term lease.',
    availableShares: 0,
    createdAt: '2025-09-12T14:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c',
    title: 'London Chelsea Townhouse',
    location: 'London, UK',
    photoUrls: [
      '/properties/london-townhouse.png',
      '/properties/london-townhouse.png',
      '/properties/london-townhouse.png',
    ],
    totalValue: 850000,
    funded: 20,
    annualYield: 4.5,
    projectedAppreciation: 5.5,
    status: 'open',
    description: 'Premium townhouse in an exclusive Chelsea square. Offers stable, high-end long-term rental income with excellent capital appreciation prospects.',
    availableShares: 900,
    createdAt: '2026-04-01T11:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d',
    title: 'Algarve Coastal Villa',
    location: 'Faro, Portugal',
    photoUrls: [
      '/properties/algarve-villa.png',
      '/properties/algarve-villa.png',
      '/properties/algarve-villa.png',
    ],
    totalValue: 600000,
    funded: 0,
    annualYield: 8.0,
    projectedAppreciation: 3.0,
    status: 'coming_soon',
    description: 'Spacious 4-bedroom villa with a private pool in the Algarve. Perfectly suited for lucrative summer holiday rentals.',
    availableShares: 1000,
    createdAt: '2026-04-10T15:30:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e',
    title: 'Munich Schwabing Flat',
    location: 'Munich, Germany',
    photoUrls: [
      '/properties/munich-flat.png',
      '/properties/munich-flat.png',
      '/properties/munich-flat.png',
    ],
    totalValue: 480000,
    funded: 60,
    annualYield: 5.1,
    projectedAppreciation: 3.9,
    status: 'open',
    description: 'Modern 2-bedroom flat in the sought-after Schwabing district. Currently leased to an international tech company for employee housing.',
    availableShares: 350,
    createdAt: '2026-01-25T08:15:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f',
    title: 'Athens Plaka Rooftop Apartment',
    location: 'Athens, Greece',
    photoUrls: [
      '/properties/athens-rooftop.png',
      '/properties/athens-rooftop.png',
      '/properties/athens-rooftop.png',
    ],
    totalValue: 250000,
    funded: 95,
    annualYield: 8.5,
    projectedAppreciation: 4.0,
    status: 'open',
    description: 'Beautiful apartment featuring a private terrace with Acropolis views. High rental yield driven by strong tourist demand.',
    availableShares: 50,
    createdAt: '2026-02-28T12:45:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'd6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a',
    title: 'Prague Old Town Loft',
    location: 'Prague, Czechia',
    photoUrls: [
      '/properties/prague-loft.png',
      '/properties/prague-loft.png',
      '/properties/prague-loft.png',
    ],
    totalValue: 290000,
    funded: 100,
    annualYield: 6.8,
    projectedAppreciation: 4.5,
    status: 'funded',
    description: 'Stylish loft conversion in Prague’s historic Old Town. Excellent occupancy rates and strong capital growth potential.',
    availableShares: 0,
    createdAt: '2025-11-05T09:30:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'e7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b',
    title: 'Lisbon Expo Modern Condo',
    location: 'Lisbon, Portugal',
    photoUrls: [
      '/properties/lisbon-expo.png',
      '/properties/lisbon-expo.png',
      '/properties/lisbon-expo.png',
    ],
    totalValue: 420000,
    funded: 10,
    annualYield: 5.8,
    projectedAppreciation: 4.2,
    status: 'open',
    description: 'Contemporary condo in Parque das Nações (Expo). Features modern amenities and river views, attracting corporate tenants.',
    availableShares: 800,
    createdAt: '2026-03-18T16:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  },
  {
    id: 'f8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c',
    title: 'Porto Boavista Penthouse',
    location: 'Porto, Portugal',
    photoUrls: [
      '/properties/porto-penthouse.png',
      '/properties/porto-penthouse.png',
      '/properties/porto-penthouse.png',
    ],
    totalValue: 510000,
    funded: 0,
    annualYield: 5.2,
    projectedAppreciation: 4.6,
    status: 'coming_soon',
    description: 'Luxurious penthouse in the upscale Boavista area. Includes a large terrace and premium finishes, targeting the high-end long-term rental market.',
    availableShares: 1000,
    createdAt: '2026-04-05T10:00:00.000Z',
    platformFee: PLATFORM_FEE_RATE,
  }
];

export const mockLocations = [
  ...new Set(mockProperties.map((p) => p.location)),
];
